name: Create Submission Report Via GitHub Action

on:
    workflow_dispatch:
permissions:
  contents: write

jobs:

  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc
      uses: pandoc/actions/setup@v1
    - name: Check pandoc version
      run: pandoc --version
    - uses: threeal/gcovr-action@v1.1.0
    - name: Create Submission Report
      run: ./github/workflows/create-report.sh
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: "Submission report created via GitHub Action"
