name: Create Submission Report Via GitHub Action

on:
    workflow_dispatch:
permissions:
  contents: write

jobs:

  report:
    runs-on: ubuntu-latest
    steps:
    - uses: threeal/gcovr-action@v1.1.0
    - name: Create Submission Report
      id: create_report
      run: |
        ./.github/workflows/create-report.sh
        echo "files=$(printf '"%s" ' submission-report.md)" > $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}
    - uses: docker://pandoc/core:3.5
      with:
        args: -s -o submission-report.docx ${{ steps.create_report.outputs.files }}

    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: "Submission report created via GitHub Action"
