name: Create Submission Report Via GitHub Action

on:
    workflow_dispatch:
permissions:
  contents: write

jobs:

  report:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
    - name: Install gcovr from pip
      run: pip install gcovr
    - uses: actions/checkout@v4
    - name: Create Submission Report
      id: create_report
      run: |
        ./.github/workflows/create-report.sh
        {
          echo 'report<<EOF'
          cat submission-report.md
          echo 'EOF'
        } >> $GITHUB_OUTPUT

    - uses: docker://pandoc/core:3.5
      with:
        args: -s -o submission-report.docx ${{ steps.create_report.outputs.report }}

    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: "Submission report created via GitHub Action"
